// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiKRmBHq9gZDBm4ZbYSufq6plEgMdF4kE',
    appId: '1:232432054892:web:b9569bc3bc5907a1a79e49',
    messagingSenderId: '232432054892',
    projectId: 'flutter-example-5f03d',
    authDomain: 'flutter-example-5f03d.firebaseapp.com',
    storageBucket: 'flutter-example-5f03d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwKk3NZRkAAmlvpdzBtZTgs7dunrrLido',
    appId: '1:232432054892:android:45bb11d1d7fb1b78a79e49',
    messagingSenderId: '232432054892',
    projectId: 'flutter-example-5f03d',
    storageBucket: 'flutter-example-5f03d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcjNcCAufszAC9KfY9GWZ_Bcvaq0l--3w',
    appId: '1:232432054892:ios:a1160a69ef0772a8a79e49',
    messagingSenderId: '232432054892',
    projectId: 'flutter-example-5f03d',
    storageBucket: 'flutter-example-5f03d.appspot.com',
    androidClientId: '232432054892-gpb0gpo3n5rllkdqk027jq2jbjheit3k.apps.googleusercontent.com',
    iosClientId: '232432054892-dmgu3m30026tq5r3lh0n807hagd2aq48.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuthPhone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcjNcCAufszAC9KfY9GWZ_Bcvaq0l--3w',
    appId: '1:232432054892:ios:0cefcd604838f7d2a79e49',
    messagingSenderId: '232432054892',
    projectId: 'flutter-example-5f03d',
    storageBucket: 'flutter-example-5f03d.appspot.com',
    androidClientId: '232432054892-gpb0gpo3n5rllkdqk027jq2jbjheit3k.apps.googleusercontent.com',
    iosClientId: '232432054892-pimd922cmtid8b51cfhc08b2qk6517p4.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuthPhone.RunnerTests',
  );
}
